name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 8 * * *'  # Runs at 8:30 AM UTC every day
  push:
    branches: [ main ]

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step with email umesh.n@gramener.com
        run: date >> daily_log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily_log.txt
          git commit -m "Automated daily commit by GitHub Actions"
          git push
