name: umesh.n@gramener.com
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 8 * * *'
    
    
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: umesh.n@gramener.com
        run: echo "Hello, world!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
