name: Daily Commit via umesh.n@gramener.com

# Trigger the workflow on a daily schedule at 08:30 UTC
on:
  schedule:
    - cron: '30 8 * * *'  # Runs every day at 08:30 UTC

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-commit:
    name: umesh.n@gramener.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable automatic GitHub token injection

      - name: Set Up Git Configuration
        run: |
          git config user.name "umesh.n"
          git config user.email "umesh.n@gramener.com"

      - name: Modify a File
        run: |
          echo "Daily update at $(date)" >> daily-log.txt

      - name: umesh.n@gramener.com
        run: echo "This step is named with your email."

      - name: Commit Changes
        run: |
          git add daily-log.txt
          git commit -m "Daily update by umesh.n@gramener.com"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
