name: Daily Commit Workflow
on:
  schedule:
    - cron: '30 8 * * *'  # Runs at 8:30 AM UTC daily

jobs:
  create-commit:
    name: umesh.n@gramener.com
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: umesh.n@gramener.com
      
      - name: Create daily commit
        run: |
          echo "Daily update $(date)" > daily-update.txt
          git config --global user.email "umesh.n@gramener.com"
          git config --global user.name "Umesh-n314"
          git add daily-update.txt
          git commit -m "Daily automated commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
